### ISSUE TITLE
Problem detecting changes

### ISSUE THREAD

**Issue by JamesCarscadden** [krosenvold/bgit#11]
I'm getting a lot of this error in my bamboo logs, and I seem to be unable to get a checkout. I can do a clone/checkout manually into the bamboo build directory. This seems to be a problem with how bgit is calling git. The relevant part of the error would appear to be: 

Error calling git-status - git status error message: { 1. error: unknown switch `a'  }

'git-status' does not exist as a separate command on my machine. 'git status' works as expected.

I'm using bamboo 2.5.2, git 1.7.0 and bgit 1.2 on Mac OS 10.6.3

com.atlassian.bamboo.repository.RepositoryException: collectChangesSinceLastBuild
    at com.atlassian.labs.bamboo.git.GitRepository.collectChangesSinceLastBuild(GitRepository.java:118)
    at com.atlassian.bamboo.v2.trigger.DefaultChangeDetectionManager.collectChangesSinceLastBuild(DefaultChangeDetectionManager.java:91)
    at com.atlassian.bamboo.v2.trigger.ChangeDetectionListenerAction.process(ChangeDetectionListenerAction.java:65)
    at com.atlassian.bamboo.build.DefaultBuildExecutionManager.tryToDetectAndBuild(DefaultBuildExecutionManager.java:99)
    at com.atlassian.bamboo.v2.trigger.ChangeDetectionListener.handleEvent(ChangeDetectionListener.java:41)
    at com.atlassian.bamboo.event.BambooEventManager$2.run(BambooEventManager.java:47)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at com.atlassian.bamboo.build.pipeline.concurrent.NamedThreadFactory$1.run(NamedThreadFactory.java:33)
    at java.lang.Thread.run(Thread.java:637)
Caused by: edu.nyu.cs.javagit.api.JavaGitException: 438000: Error calling git-status - git status error message: { 1. error: unknown switch `a'  }
    at edu.nyu.cs.javagit.client.cli.CliGitStatus$GitStatusParser.getResponse(CliGitStatus.java:428)
    at edu.nyu.cs.javagit.client.cli.CliGitStatus$GitStatusParser.getResponse(CliGitStatus.java:228)
    at edu.nyu.cs.javagit.client.cli.ProcessUtilities.runCommand(ProcessUtilities.java:146)
    at edu.nyu.cs.javagit.client.cli.CliGitStatus.status(CliGitStatus.java:82)
    at edu.nyu.cs.javagit.client.cli.CliGitStatus.status(CliGitStatus.java:103)
    at edu.nyu.cs.javagit.api.commands.GitStatus.status(GitStatus.java:100)
    at com.atlassian.labs.bamboo.git.GitRepository.getGitStatusResponse(GitRepository.java:315)
    at com.atlassian.labs.bamboo.git.GitRepository.gitStatus(GitRepository.java:307)
    at com.atlassian.labs.bamboo.git.GitRepository.reallyCloneOrFetch(GitRepository.java:418)
    at com.atlassian.labs.bamboo.git.GitRepository.cloneOrFetch(GitRepository.java:368)
    at com.atlassian.labs.bamboo.git.GitRepository.collectChangesSinceLastBuild(GitRepository.java:103)
    ... 9 more

Any fixes or work arounds?

**Comment by Blizzke** [comment]
Did manage to get a solution for this? I have exactly the same problem....

**Comment by krosenvold** [comment]
Please build latest from source, test and respond back if this problem is fixed.

**Comment by Blizzke** [comment]
That did the trick... My build still fails but it's no longer a git related thing :-) 
Thanks for the quick response!

**Comment by krosenvold** [comment]
This'll be release as 1.2.1 as soon as I hear from the other 2 issues

**Comment by JamesCarscadden** [comment]
Yeah, I actually compiled from source a week or two ago, after I saw the commit message relating to the 'a' switch. The fix worked for me as well - guess I forgot to post back. Naughty naughty.

**Comment by digitalmedia** [comment]
Hi Kristian, is there a binary available for v1.2.1? I don't have a build env for this setup, and have been unable to run Bamboo with the "status -a" error.
Thanks man,
- Richard (digitalmedia)

**Comment by digitalmedia** [comment]
Please ignore my request, installed maven and built it myself. Thanks.

**Comment by krosenvold** [comment]
I'm publishing 1.2.2 binary as soon as github lets me upload again
