### ISSUE TITLE
git-reset error during collectChangesSinceLastBuild

### ISSUE THREAD

**Issue by mkemme** [krosenvold/bgit#12]
We have several repositories for which we get frequent "git-reset" errors. We are using latest version of the plugin: git-plugin-1.2.jar (downloaded jar file)

Stack trace follows:
Caused by: edu.nyu.cs.javagit.api.JavaGitException: 432000: Error calling git-reset.  The git-reset error message:  { line1=[], line2=[HEAD is now at 64b50ee... Exporta poga pie aktivitates, exporta formatejums] }
    at edu.nyu.cs.javagit.client.cli.CliGitReset$GitResetParser.getResponse(CliGitReset.java:190)
    at edu.nyu.cs.javagit.client.cli.CliGitReset$GitResetParser.getResponse(CliGitReset.java:110)
    at edu.nyu.cs.javagit.client.cli.ProcessUtilities.runCommand(ProcessUtilities.java:146)
    at edu.nyu.cs.javagit.client.cli.CliGitReset.resetProcessor(CliGitReset.java:76)
    at edu.nyu.cs.javagit.client.cli.CliGitReset.gitReset(CliGitReset.java:46)
    at edu.nyu.cs.javagit.api.commands.GitReset.gitReset(GitReset.java:104)
    at com.atlassian.labs.bamboo.git.GitRepository.reallyCloneOrFetch(GitRepository.java:424)
    at com.atlassian.labs.bamboo.git.GitRepository.cloneOrFetch(GitRepository.java:368)
    at com.atlassian.labs.bamboo.git.GitRepository.collectChangesSinceLastBuild(GitRepository.java:103)
    ... 10 more

Please suggest some fixes or workarounds.

**Comment by krosenvold** [comment]
This seems like a bug in the parsing of the git reset command. If you're in  a hurry you need to fix this yourself, it'll be a few days before I have time to look at it.

**Comment by krosenvold** [comment]
I'm seeing this problem myself now and It's either related to many concurrent gits or a bug in newer versions of git (probably >= 1.7). Please try downgrading to a 1.6.X and see if it helps, and please report back

**Comment by krosenvold** [comment]
My problem turned out to be caused by full disk (no more i-nodes). Maybe something to check ?

**Comment by mkemme** [comment]
Regarding disk space - everything is ok with it.
Checked out git version - it is 1.5.2.1. Could this be a problem?

**Comment by mkemme** [comment]
Kristian, do you suggest upgrade from 1.5.x to 1.6.x? There are no ready v1.6 RPMS for our CI server platform and this will take some time for us.

**Comment by krosenvold** [comment]
It still feels like you have a problem with permissions, running out of i-nodes or disk space. Check df -i as well and make sure you're not at 90% disk space or anywhere close. Also look for permission problems. 

I am not totally convinced upgrading will help you. Actually the opposite ;)

**Comment by krosenvold** [comment]
I've tried a fix for this issue (CliGitReset line 171). If you build the latest version from master it may fix your problem

**Comment by mkemme** [comment]
Kristian,
lately we had an idea that this breakdown is related to special characters used in log messages. Good news is that we installed your patch and ... it seems that the fix works! Thank you!
