### ISSUE TITLE
Caused by: java.io.IOException: 020001: File or path does not exist.  { filename=[checkout] } 

### ISSUE THREAD

**Issue by trevormarshall** [krosenvold/bgit#15]
hi, we are seeing this in a dependant build. Bamboo 2.5.5, git-plugin-1.2.2-SNAPSHOT.jar, git 1.6.4:
Is this a plugin issue?

com.atlassian.bamboo.repository.RepositoryException: collectChangesSinceLastBuild
    at com.atlassian.labs.bamboo.git.GitRepository.collectChangesSinceLastBuild(GitRepository.java:115)
    at com.atlassian.bamboo.v2.trigger.DefaultChangeDetectionManager.collectChangesSinceLastBuild(DefaultChangeDetectionManager.java:91)
    at com.atlassian.bamboo.v2.trigger.DependentBuildDetectionAction.findBuildChanges(DependentBuildDetectionAction.java:122)
    at com.atlassian.bamboo.v2.trigger.DependentBuildDetectionAction.process(DependentBuildDetectionAction.java:71)
    at com.atlassian.bamboo.build.DefaultBuildExecutionManager.tryToDetectAndBuild(DefaultBuildExecutionManager.java:99)
    at com.atlassian.bamboo.v2.trigger.DependencyBuildListener.handleEvent(DependencyBuildListener.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:304)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)
    at org.springframework.orm.hibernate.HibernateInterceptor.invoke(HibernateInterceptor.java:117)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at $Proxy52.handleEvent(Unknown Source)
    at com.atlassian.bamboo.event.BambooEventManager$2.run(BambooEventManager.java:47)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at com.atlassian.bamboo.build.pipeline.concurrent.NamedThreadFactory$1.run(NamedThreadFactory.java:33)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.io.IOException: 020001: File or path does not exist.  { filename=[checkout] }
    at edu.nyu.cs.javagit.utilities.CheckUtilities.checkFileValidity(CheckUtilities.java:53)
    at edu.nyu.cs.javagit.client.cli.CliGitSubmodule.init(CliGitSubmodule.java:20)
    at com.atlassian.labs.bamboo.git.GitRepository.submodule_update(GitRepository.java:352)
    at com.atlassian.labs.bamboo.git.GitRepository.reallyCloneOrFetch(GitRepository.java:418)
    at com.atlassian.labs.bamboo.git.GitRepository.cloneOrFetch(GitRepository.java:384)
    at com.atlassian.labs.bamboo.git.GitRepository.collectChangesSinceLastBuild(GitRepository.java:103)
    ... 21 more

Thanks,
Trevor

**Comment by krosenvold** [comment]
Just try deleting the local "checkout" folder. If the problem persists, you might have a permissions problem. Try cloning with the same user to the same folder and see what happens.

**Comment by trevormarshall** [comment]
Thanks Kristian, that seems to work, though the issue has resurfaced again for at least one plan after removing the directory. We cloned that plan and are monitoring.

Best regards,
Trevor

**Comment by trevormarshall** [comment]
Am still seeing this regularly. Just created an entirely new project and plan and got it on the first build. Permissions look fine. Any suggestions?

Cheers,
Trevor

com.atlassian.bamboo.repository.RepositoryException: retrieveSourceCode
    at com.atlassian.labs.bamboo.git.GitRepository.retrieveSourceCode(GitRepository.java:155)
    at com.atlassian.bamboo.v2.build.task.CheckoutUpdateForBuild.call(CheckoutUpdateForBuild.java:100)
    at sun.reflect.GeneratedMethodAccessor594.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:304)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)
    at org.springframework.orm.hibernate.HibernateInterceptor.invoke(HibernateInterceptor.java:117)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at $Proxy241.call(Unknown Source)
    at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:188)
    at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:90)
    at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:101)
    at com.atlassian.bamboo.build.pipeline.concurrent.NamedThreadFactory$1.run(NamedThreadFactory.java:33)
    at java.lang.Thread.run(Thread.java:619)
Caused by: java.io.IOException: 020001: File or path does not exist.  { filename=[checkout] }
    at edu.nyu.cs.javagit.utilities.CheckUtilities.checkFileValidity(CheckUtilities.java:53)
    at edu.nyu.cs.javagit.client.cli.CliGitSubmodule.init(CliGitSubmodule.java:20)
    at com.atlassian.labs.bamboo.git.GitRepository.submodule_update(GitRepository.java:352)
    at com.atlassian.labs.bamboo.git.GitRepository.reallyCloneOrFetch(GitRepository.java:418)
    at com.atlassian.labs.bamboo.git.GitRepository.cloneOrFetch(GitRepository.java:388)
    at com.atlassian.labs.bamboo.git.GitRepository.retrieveSourceCode(GitRepository.java:151)
    ... 16 more

**Comment by krosenvold** [comment]
I think the real source of this problem lies a bit earlier in the log, by the time you're getting this message it's too late. The submodule logic require;s that the initial clone went well, which it seemingly did not - for reasons unknown ;) Maybe you can find a hint somewhere earlier ?

**Comment by trevormarshall** [comment]
Hi Kristian, you're right, though there is no indicator earlier in the log that I can see. A complete patch of the server, git, Bamboo and plugins seems to have cured it.

Cheers,
Trevor
